// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShepardsPiesAPI.Data;

#nullable disable

namespace ShepardsPiesAPI.Migrations
{
    [DbContext(typeof(ShepardsPiesDbContext))]
    [Migration("20250529195940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShepardsPiesAPI.Models.CheeseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CheeseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buffalo Mozzarella"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Four Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Claudia Romano",
                            PhoneNum = "5551234567"
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeliverer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeliverer = false,
                            Name = "Joe"
                        },
                        new
                        {
                            Id = 2,
                            IsDeliverer = true,
                            Name = "Frankie"
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveredByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TakenByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveredByEmployeeId");

                    b.HasIndex("TakenByEmployeeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            TableNumber = 12,
                            TakenByEmployeeId = 1,
                            TipAmount = 4.00m,
                            TotalCost = 27.00m
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PizzaCheeseId")
                        .HasColumnType("integer");

                    b.Property<int>("PizzaSauceId")
                        .HasColumnType("integer");

                    b.Property<int>("PizzaSizeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPizzaPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaCheeseId");

                    b.HasIndex("PizzaSauceId");

                    b.HasIndex("PizzaSizeId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            PizzaCheeseId = 1,
                            PizzaSauceId = 1,
                            PizzaSizeId = 2,
                            TotalPizzaPrice = 12.50m
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.PizzaSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Diameter")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PizzaSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = 10,
                            Name = "Small",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            Diameter = 14,
                            Name = "Medium",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            Diameter = 18,
                            Name = "Large",
                            Price = 15.00m
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.PizzaTopping", b =>
                {
                    b.Property<int>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<int>("ToppingId")
                        .HasColumnType("integer");

                    b.HasKey("PizzaId", "ToppingId");

                    b.HasIndex("ToppingId");

                    b.ToTable("PizzaTopping");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            ToppingId = 2
                        },
                        new
                        {
                            PizzaId = 1,
                            ToppingId = 3
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.SauceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SauceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marinara"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arrabbiata"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Garlic White"
                        },
                        new
                        {
                            Id = 4,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToppingPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sausage",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepperoni",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mushroom",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Onion",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Green Pepper",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Black Olive",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Basil",
                            ToppingPrice = 0.50m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Extra Cheese",
                            ToppingPrice = 0.50m
                        });
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Order", b =>
                {
                    b.HasOne("ShepardsPiesAPI.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardsPiesAPI.Models.Employee", "DeliveredByEmployee")
                        .WithMany()
                        .HasForeignKey("DeliveredByEmployeeId");

                    b.HasOne("ShepardsPiesAPI.Models.Employee", "TakenByEmployee")
                        .WithMany()
                        .HasForeignKey("TakenByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveredByEmployee");

                    b.Navigation("TakenByEmployee");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Pizza", b =>
                {
                    b.HasOne("ShepardsPiesAPI.Models.Order", "Order")
                        .WithMany("Pizzas")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardsPiesAPI.Models.CheeseType", "PizzaCheese")
                        .WithMany("Pizzas")
                        .HasForeignKey("PizzaCheeseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardsPiesAPI.Models.SauceType", "PizzaSauce")
                        .WithMany("Pizzas")
                        .HasForeignKey("PizzaSauceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardsPiesAPI.Models.PizzaSize", "PizzaSize")
                        .WithMany("Pizzas")
                        .HasForeignKey("PizzaSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PizzaCheese");

                    b.Navigation("PizzaSauce");

                    b.Navigation("PizzaSize");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.PizzaTopping", b =>
                {
                    b.HasOne("ShepardsPiesAPI.Models.Pizza", "Pizza")
                        .WithMany("PizzaToppings")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardsPiesAPI.Models.Topping", "Topping")
                        .WithMany("PizzaToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.CheeseType", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Order", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Pizza", b =>
                {
                    b.Navigation("PizzaToppings");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.PizzaSize", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.SauceType", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("ShepardsPiesAPI.Models.Topping", b =>
                {
                    b.Navigation("PizzaToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
